[Features]
coloredCobblestone = false
darkGlass = false
emeraldGear = false
flintGear = false
magnet = false
meshes = false
nightVisionGoggles = false
paxels = false
rightClickHarvest = false
smoothGlowstone = false
wateringCan = false
["Grid Repair"]
enabled = false
[Tweaks]
toolBreaking = false
