[client]
[client.window]
simple_title = "[${mcversion}] - Minecraft Team Resourceful"
title = "[${mcversion}] - Minecraft Team Resourceful"
title_with_activity = "[${mcversion}] - Minecraft Team Resourceful - ${activity}"
[connection_timeouts]
keep_alive_timeout_seconds = 180
login_timeout_ticks = 12000
[misc]
mixin_blacklist = ["ServerPlayNetHandlerKeepAlive"]
