["Add New Version"]
#Version Number. VersionNumbers are simple Integers. Use a number larger than the last version.
newVersion = 0
#ModID's of the ServerConfigs that will be deleted when a world with a version lower than this version is omma Seploaded the first time. Carated list. (ServerConfig without -server.toml)
toDelete = ""
["File Deleter"]
#This is intended for deleting datapacks and/or craft tweaker scripts. The file will be deleted every launch if it exists! No access to saves or world folder. Specify the path to the file. Comma Separated List. Example: scripts/badscript.zs
filesToDelete = ""
